version: '3'

services:
  web:
    build: .
    image: rogermonteiro/flask_app:latest
    command: python -u app.py
    ports:
      - 80:5000
    networks:
      - mynet
    links:
      - mongo
      - elasticsearch
    depends_on:
      - mongo
    #deploy:
    #  placement:
    #    constraints: [node.role == worker]


  mongo:
    image: mongo:3.6
    networks:
      - mynet
    ports:
      - 27017:27017
    #volumes:
    #  - ./data:/data/db
    #deploy:
    #    placement:
    #        constraints: [node.role == manager]

  elasticsearch:
    #container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    environment:
      - xpack.security.enabled=false
      - node.name=es01
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      -  esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - mynet

volumes:
  esdata:
    driver: local
    
networks:
  mynet:
