apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kibana
  name: kibana-service
spec:
  ports:
  - name: "5601"
    port: 5601
    targetPort: 5601
  type: NodePort
  selector:
    io.kompose.service: kibana
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kibana
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name : kibana
        io.kompose.service: kibana
    spec:
      containers:
      - env:
        - name: xpack.security.enabled
          value: "false"
        image: docker.elastic.co/kibana/kibana:6.8.9
        name: kibana
        ports:
        - containerPort: 5601
        resources: {}
      restartPolicy: Always
status: {}
